# Generated by Django 4.1.7 on 2023-04-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0002_alter_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('caption', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('college', models.CharField(max_length=200)),
                ('sdate', models.DateTimeField()),
                ('edate', models.DateTimeField()),
                ('post_images', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
