# Generated by Django 4.1.7 on 2023-04-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isAdmin',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
